### PR TITLE
fixed tab bar and image display, made things look a bit nicer

### LINKED ISSUE #10: MVP: Prevent TabBar from scrolling vertically
Selecting the TabBar while scrolling lets the user scroll it out of view, which isn't ideal. Everything should stay put.

Current behavior: 
image
image

Desired behavior:
image

### PR DESCRIPTION
**Pull request by daniel-n6**
fixes #10, also fixes ink effect so that it displays over images, changed display of post cards so it looks a bit nicer, gets rid of scroll-to-top button since it's a little buggy

### CODE REVIEW

File: lib/ui/list/infinite_list.dart [hunk 1]
```diff
@@ -1,3 +1,4 @@
+/*
```
Comment (GreenCappuccino) [inline lib/ui/list/infinite_list.dart:1]: Ok, i see that this has been commented out... did something break because of this? I personally wanted to make a generic infinite list so I could repurpose the code for like search results and comments.... but like if its not convention then ig we can remove it.

**Comment by GreenCappuccino** [comment]
introduces #25

File: lib/ui/list/infinite_list.dart (hunk 1 above)
Comment (daniel-n6) [reply lib/ui/list/infinite_list.dart:1]: I commented it out bc mainly bc I was just trying to find a quick way to implement it for the posts list view, I felt like the infinite list only made things more complicated

**Review by GreenCappuccino — APPROVED** [review]
